language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn run lerna run prepublish
script:
  - yarn test
# deploy:
#   provider: script
#   script: "yarn run lerna:publish"
#   skip_cleanup: true
#   on:
#     node: "10"
#     branch: release
