language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn run lerna run prepublish
script:
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
